# Generated by Django 4.2 on 2023-04-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_author_task_authorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='authorid',
            new_name='author_id',
        ),
    ]
